### ISSUE TITLE
Want to know more about this line

### ISSUE THREAD

**Issue by bharatpatil** [michaelsoriano/wp-vue-starter#3]
https://github.com/michaelsoriano/wp-vue-starter/blob/a6b8bc2c74f227eba025b5b794f66920829312e8/functions.php#L32

Hello, I just wanted to know more about these lines till line 36. What is happening here.

**Comment by michaelsoriano** [comment]
That's doing a [curl ](http://php.net/manual/en/book.curl.php)call to $url (which is a WP REST endpoint). Getting the response back in json ($result).

**Comment by bharatpatil** [comment]
thanks may be I should have specified. I wanted to understand the significance of it.

**Comment by michaelsoriano** [comment]
It's when you're creating a post and you click "preview". The theme will render the "preview" mode of your post.

**Comment by bharatpatil** [comment]
ohk thanks a lot. I had guessed the same however it isn’t working in my case. Getting the empty response.

**Comment by michaelsoriano** [comment]
hmm. is there an error? when you print_r - is the whole object empty? or just parts of it? we're particularly looking for the following:

` $postarray[0]->title->rendered ;
 $postarray[0]->content->rendered  
`

**Comment by bharatpatil** [comment]
yes. Response is always empty, if I print_r the whole object is empty.
